### PR TITLE
Modernise to GHC 9

### PR DESCRIPTION
**Pull request by emberdart**
Also adds Nix and dotenvrc stuff, along with using hlint and stylish-haskell

### CODE REVIEW

**Comment by CLowcay** [comment]
Thank you for the pull request.  I saw the issue that you raised and I pushed some updates to master, but I didn't know you had a pull request coming.  Now there's a merge conflict.  I do apologize for that.  If you'd like to rebase your changes on master I'd be happy to merge.

As for the formatting, I'm using Ormolu for everything these days.

**Comment by emberdart** [comment]
Fair enough, I'll pull in and go with it.

**Comment by emberdart** [comment]
This was just my branch for making it work for me, by adding Nix stuff. I haven't figured out about making it go to GHC 9 yet.

**Comment by emberdart** [comment]
Could you make a new release to hackage with these please?

**Pull request merged**
